### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by vucsetadavid** [likehopper/redmine_sla#1]
Hello, after we install this plugin, we get this error. Can you help me?

App 2713508 output: Error: The application encountered the following error: expected file /opt/redmine/redmine-5.0.3/plugins/redmine_sla/app/models/sla_journal.rb to define constant SlaJournal, but didn't (Zeitwerk::NameError)
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:28:in `require'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader/helpers.rb:127:in `cget'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader.rb:239:in `block (2 levels) in eager_load'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader/helpers.rb:27:in `each'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader/helpers.rb:27:in `ls'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader.rb:234:in `block in eager_load'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader.rb:219:in `synchronize'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader.rb:219:in `eager_load'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader.rb:318:in `each'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.6.1/lib/zeitwerk/loader.rb:318:in `eager_load_all'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in '
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
App 2713508 output: /opt/redmine/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
App 2713508 output: /opt/redmine/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 2713508 output: /opt/redmine/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 2713508 output: /opt/redmine/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 2713508 output: /opt/redmine/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
App 2713508 output: /opt/redmine/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
App 2713508 output: /opt/redmine/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
App 2713508 output: /opt/redmine/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
App 2713508 output: /opt/redmine/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
App 2713508 output: /opt/redmine/redmine-5.0.3/config/environment.rb:16:in `'
App 2713508 output: [config.ru:3](http://config.ru:3/):in `require'
App 2713508 output: [config.ru:3](http://config.ru:3/):in `block in '
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/rack-2.2.4/lib/rack/builder.rb:125:in `instance_eval'
App 2713508 output: /opt/redmine/.rvm/gems/ruby-2.7.2/gems/rack-2.2.4/lib/rack/builder.rb:125:in `initialize'
App 2713508 output: [config.ru:1](http://config.ru:1/):in `new'
App 2713508 output: [config.ru:1](http://config.ru:1/):in `<main>'
App 2713508 output: /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
App 2713508 output: /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 2713508 output: /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 2713508 output: /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 2713508 output: /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 2713508 output: /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 2713508 output: /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2023-06-07 10:32:57.0745 2713324/Tw age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/redmine/redmine: The application encountered the following error: expected file /opt/redmine/redmine-5.0.3/plugins/redmine_sla/app/models/sla_journal.rb to define constant SlaJournal, but didn't (Zeitwerk::NameError)
Error ID: ce717fa5
Error details saved to: /tmp/passenger-error-RCF1t3.html

**Comment by likehopper** [comment]
I do not reproduce yet and this model is not really used. Still, to test, could you try renaming the "app/models/sla_journal.rb" file to "app/models/sla_view_journal.rb"?
(if you are in the redmine folder, you can run this command `mv plugins/redmine_sla/app/models/sla_journal.rb plugins/redmine_sla/app/models/sla_view_journal.rb` ).

**Comment by baherdev** [comment]
Hi,

In my case I confirm when I changed from sla_journal.rb to sla_view_journal.rb it works.

**Comment by vucsetadavid** [comment]
It's worked for me too.

**Comment by likehopper** [comment]
Commint Align file name to model name
