### ISSUE TITLE
db:migrate error with redmine 5.1.2

### ISSUE THREAD

**Issue by gu1llohm** [likehopper/redmine_sla#16]
Dear likehopper, 

I'm trying to migrate db : RAILS_ENV=production rake redmine:plugins:migrate NAME=redmine_sla

but i'm getting for 202111112021001: 

Mysql2::Error: BLOB/TEXT column 'name' used in key specification without a key length (Mysql2::Error)

is it possible to tell me how to patch sql migration ? 

THanks !

**Comment by likehopper** [comment]
Currently, the plugin requires a PostgreSQL database.
[The ](https://github.com/likehopper/redmine_sla#prerequisites)

I have planned enhancements, but support for MySQL isn't included yet.
https://github.com/likehopper/redmine_sla/issues/2#issuecomment-1588043305

You can easily migrate Redmine from MySQL to PostgreSQL. Personally, I use this configuration file with PgLoader :
https://github.com/likehopper/redmine_sla/files/13997344/redmine_migration.txt
