### ISSUE TITLE
Problems with caches 

### ISSUE THREAD

**Issue by SerhiiZahuba** [likehopper/redmine_sla#17]
Hello. Can you help me with plugins ?
After installing the plugin if I go to the projects/test_project/sla/caches link I see an error

`Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

[Back](javascript:history.back())`

In my log

![image](https://github.com/user-attachments/assets/f7fa9063-500c-4f75-b681-5c6928010157)

**Comment by likehopper** [comment]
Yes, what version of Redmine are you using?

**Comment by likehopper** [comment]
I probably found the issue with CSV separator selection in 5.1 of Redmine.
I push a fix to handle this exception in previous Redmine versions.
Can you pull the latest version of the code and test it?
