### ISSUE TITLE
Problem with MySQL

### ISSUE THREAD

**Issue by maciejbtc** [likehopper/redmine_sla#2]
Hello,

I have a problem with migration on MySQL:
[root@centos7 redmine]# bundle exec rake redmine:plugins:migrate NAME=redmine_sla RAILS_ENV=production
/opt/rh/rh-ruby25/root/usr/share/gems/gems/psych-3.1.0/lib/psych.rb:237: warning: already initialized constant Psych::LIBYAML_VERSION
/opt/rh/rh-ruby25/root/usr/share/ruby/psych.rb:232: warning: previous definition of LIBYAML_VERSION was here
== 202111112021001 CreateSlas: migrating ======================================
-- create_table(:slas, {})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
**Mysql2::Error: BLOB/TEXT column 'name' used in key specification without a key length**

Is there any chance to fix it?

**Comment by likehopper** [comment]
For this start, for performance reasons, the plugin only works on a PostgreSQL database using its strengths ( cf. https://github.com/likehopper/redmine_sla/blob/main/README.md#prerequisites ).
Indeed, the calculation of the SLAs is based on the use of the generate_series function of PostgreSQL ( cf. https://github.com/likehopper/redmine_sla/blob/main/doc/COMPUTE.md ).
Yet, a contributor tries to adapt the plugin to MySQL... I'll let you know !

**Comment by gu1llohm** [comment]
thank you very much @likehopper for your quick response.
