### ISSUE TITLE
error when i want migrate

### ISSUE THREAD

**Issue by vucsetadavid** [likehopper/redmine_sla#4]
Hello,

When i want to run the rake command for migration, we get this error:

redmine@redmine:~/redmine$ rake redmine:plugins:migrate NAME=redmine_sla
rake aborted!
LoadError: cannot load such file -- listen
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `req                                                                             uire'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `req                                                                             uire'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:                                                                             in `require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:332:in `block in require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:299:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:332:in `require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             evented_file_update_checker.rb:6:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `req                                                                             uire'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `req                                                                             uire'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:                                                                             in `require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:332:in `block in require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:299:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:332:in `require'
/opt/redmine/redmine-5.0.5/config/environments/development.rb:58:in `block in <t                                                                             op (required)>'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/railtie.rb:234                                                                             :in `instance_eval'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/railtie.rb:234                                                                             :in `configure'
/opt/redmine/redmine-5.0.5/config/environments/development.rb:5:in `<top (requir                                                                             ed)>'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `req                                                                             uire'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `req                                                                             uire'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:                                                                             in `require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:332:in `block in require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:299:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:332:in `require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/engine.rb:571:                                                                             in `block (2 levels) in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/engine.rb:570:                                                                             in `each'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/engine.rb:570:                                                                             in `block in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/initializable.                                                                             rb:32:in `instance_exec'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/initializable.                                                                             rb:32:in `run'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/initializable.                                                                             rb:61:in `block in run_initializers'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/initializable.                                                                             rb:50:in `each'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/initializable.                                                                             rb:50:in `tsort_each_child'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/initializable.                                                                             rb:60:in `run_initializers'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/application.rb                                                                             :391:in `initialize!'
/opt/redmine/redmine-5.0.5/config/environment.rb:16:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `req                                                                             uire'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `req                                                                             uire'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:                                                                             in `require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:332:in `block in require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:299:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/activesupport-6.1.7.2/lib/active_support/                                                                             dependencies.rb:332:in `require'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/application.rb                                                                             :367:in `require_environment!'
/opt/redmine/.rvm/gems/ruby-3.1.4/gems/railties-6.1.7.2/lib/rails/application.rb                                                                             :533:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

The system information: 
Environment:
  Redmine version                5.0.5.stable
  Ruby version                   3.1.4-p223 (2023-03-30) [x86_64-linux]
  Rails version                  6.1.7.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Redminex_theme
SCM:
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  000_redmine_x_ux_upgrade       1.3.11
  additional_tags                1.0.7
  additionals                    3.0.8
  redmine_agile                  1.6.4
  redmine_automation             3.0.8
  redmine_checklists             3.1.22
  redmine_contacts               4.3.7
  redmine_contacts_helpdesk      4.2.1
  redmine_issue_templates        1.1.2
  redmine_reporting              3.0.8
  redmine_subtasks_inherited_fields 1.2.0
  redmine_x_lightbox2            1.0.0
  redmine_xlsx_format_issue_exporter 0.2.0
`

**Comment by likehopper** [comment]
I understand that the polyglot gem is missing. This gem isn't required for the redmine_sla plugin. The dependency should be from another plugin. Redmine and these plugins are functional whitout redmine_sla ?

**Comment by likehopper** [comment]
I suspect then a problem with the version of Rails.  I need to install an iso environment, except others plugins, to verify this.

**Comment by likehopper** [comment]
So I left with this setup:

![Capture d’écran du 2023-07-28 22-39-45](https://github.com/likehopper/redmine_sla/assets/12208142/043edfee-87c0-4fa0-a9a0-0e743a8d8775)


I did not encounter any problem while reinstalling everything.

Could you run the following commands:
- `bundler update`
- `bundler install`

And give me the output of the command `gem list`. 
Here's mine : [redmine5-gem_list.txt](https://github.com/likehopper/redmine_sla/files/12198208/redmine5-gem_list.txt)

**Comment by vucsetadavid** [comment]
After the bundler update and bundler install command a get the same error.
The gem list:

*** LOCAL GEMS ***

abbrev (default: 0.1.0)
actioncable (6.1.7.2)
actionmailbox (6.1.7.2)
actionmailer (6.1.7.2)
actionpack (6.1.7.2)
actionpack-xml_parser (2.0.1)
actiontext (6.1.7.2)
actionview (6.1.7.2)
activejob (6.1.7.2)
activemodel (6.1.7.2)
activerecord (6.1.7.2)
activestorage (6.1.7.2)
activesupport (6.1.7.2)
acts-as-taggable-on (9.0.1)
additional_tags (1.0.7)
addressable (2.8.5, 2.8.4)
ast (2.4.2)
base64 (default: 0.1.1)
benchmark (default: 0.2.0)
better_errors (2.10.1)
bigdecimal (default: 3.1.1)
binding_of_caller (1.0.0)
builder (3.2.4)
bundler (default: 2.3.26)
bundler-unload (1.0.2)
business_time (0.13.0)
capybara (3.38.0)
cgi (default: 0.3.6)
chef-utils (18.2.7)
childprocess (3.0.0)
chronic (0.10.2)
chronic_duration (0.10.6)
chunky_png (1.4.0)
commonmarker (0.23.10, 0.23.9)
composite_primary_keys (13.0.7)
concurrent-ruby (1.2.2)
crass (1.0.6)
css_parser (1.14.0)
csv (3.2.7, default: 3.2.5)
date (default: 3.2.2)
debug (1.6.3)
debug_inspector (1.1.0)
deckar01-task_list (2.3.2)
deep_cloneable (3.2.0)
deface (1.9.0)
delegate (default: 0.2.0)
did_you_mean (default: 1.6.1)
digest (3.1.1, default: 3.1.0)
docile (1.4.0)
drb (default: 2.1.0)
edge_rider (2.3.0)
english (default: 0.7.1)
erb (default: 2.2.3)
error_highlight (default: 0.3.0)
erubi (1.12.0)
et-orbi (1.2.7)
etc (default: 1.3.0)
executable-hooks (1.6.1)
fcntl (default: 1.0.1)
ffi (1.15.5)
fiddle (default: 1.1.0)
fileutils (default: 1.6.0)
find (default: 0.1.1)
forwardable (default: 1.3.2)
fugit (1.8.1)
gem-wrappers (1.4.0)
getoptlong (default: 0.1.1)
globalid (1.1.0)
html-pipeline (2.13.2)
htmlentities (4.3.4)
i18n (1.10.0)
io-console (default: 0.5.11)
io-nonblock (default: 0.1.0)
io-wait (default: 0.2.1)
ipaddr (default: 1.2.4)
irb (default: 1.4.1)
json (default: 2.6.1)
liquid (2.6.3)
listen (3.8.0)
logger (default: 1.5.0)
loofah (2.21.3)
mail (2.7.1)
marcel (1.0.2)
matrix (0.4.2)
method_source (1.0.0)
mini_magick (4.11.0)
mini_mime (1.1.5, 1.1.2)
minidusen (0.10.1)
minitest (5.19.0, 5.18.1, 5.15.0)
mixlib-shellout (3.2.7)
mocha (2.0.4)
money (6.16.0)
mutex_m (default: 0.1.1)
nested_form (0.3.2)
net-ftp (0.1.3)
net-http (default: 0.3.0)
net-imap (0.2.3)
net-ldap (0.17.1)
net-pop (0.1.2, 0.1.1)
net-protocol (0.2.1, default: 0.1.2)
net-smtp (0.3.3, 0.3.1)
nio4r (2.5.9)
nkf (default: 0.1.1)
nokogiri (1.13.10 x86_64-linux)
numerizer (0.1.1)
observer (default: 0.1.1)
open-uri (default: 0.2.0)
open3 (default: 0.1.1)
openssl (default: 3.0.1)
optparse (default: 0.2.0)
ostruct (default: 0.5.2)
parallel (1.23.0)
parser (3.2.2.3)
pathname (default: 0.2.0)
pg (1.2.3)
polyglot (0.3.5)
power_assert (2.0.1)
pp (default: 0.3.0)
prettyprint (default: 0.1.1)
prime (0.1.2)
pstore (default: 0.1.1)
psych (default: 4.0.4)
public_suffix (5.0.3)
puma (6.3.0)
raabro (1.4.0)
racc (1.7.1, default: 1.6.0)
rack (2.2.8, 2.2.7)
rack-test (2.1.0)
rails (6.1.7.2)
rails-dom-testing (2.2.0, 2.1.1)
rails-html-sanitizer (1.5.0)
railties (6.1.7.2)
rainbow (3.1.1)
rake (13.0.6)
rb-fsevent (0.11.2)
rb-inotify (0.10.1)
rbpdf (1.21.3)
rbpdf-font (1.19.1)
rbs (2.7.0)
rdoc (default: 6.4.0)
readline (default: 0.0.3)
readline-ext (default: 0.1.4)
redcarpet (3.5.1)
redmine_crm (0.0.59)
redmine_plugin_kit (1.0.4)
regexp_parser (2.8.1)
reline (default: 0.3.1)
render_async (2.1.11)
request_store (1.5.1)
resolv (default: 0.2.1)
resolv-replace (default: 0.1.0)
rexml (3.2.6, 3.2.5)
rinda (default: 0.1.1)
roadie (5.1.0)
roadie-rails (3.0.0)
rotp (6.2.2)
rouge (3.28.0)
rqrcode (2.2.0)
rqrcode_core (1.2.0)
rss (0.2.9)
rubocop (1.26.1)
rubocop-ast (1.29.0)
rubocop-performance (1.13.3)
rubocop-rails (2.14.2)
ruby-ole (1.2.12.2)
ruby-progressbar (1.13.0)
ruby2_keywords (default: 0.0.5)
rubygems-bundler (1.4.5)
rubyzip (2.3.2)
rvm (1.11.3.9)
sanitize (6.0.2)
securerandom (default: 0.2.0)
selenium-webdriver (3.142.7)
set (default: 1.0.2)
shellwords (default: 0.1.0)
simplecov (0.21.2)
simplecov-html (0.12.3)
simplecov_json_formatter (0.1.4)
singleton (default: 0.1.1)
slim (5.1.1)
slim-rails (3.6.2)
spreadsheet (1.3.0)
sprockets (4.2.0)
sprockets-rails (3.4.2)
stringio (default: 3.0.1)
strscan (3.0.6, default: 3.0.1)
syslog (default: 0.1.0)
tanuki_emoji (0.6.0)
tempfile (default: 0.1.2)
temple (0.10.2)
test-unit (3.5.3)
thor (1.2.2)
tilt (2.2.0)
time (default: 0.2.2)
timeout (0.4.0, default: 0.2.0)
tmpdir (default: 0.1.2)
tsort (default: 0.1.0)
typeprof (0.21.3)
tzinfo (2.0.6)
un (default: 0.2.0)
unicode-display_width (2.4.2)
uri (default: 0.12.1)
vcard (0.3.0)
weakref (default: 0.1.1)
webdrivers (4.6.1)
websocket-driver (0.7.6, 0.7.5)
websocket-extensions (0.1.5)
whenever (1.0.0)
write_xlsx (1.11.0)
xpath (3.2.0)
yaml (default: 0.2.0)
yard (0.9.34)
zeitwerk (2.6.11, 2.6.8)
zlib (default: 2.1.1)

**Comment by likehopper** [comment]
Sorry, I don't see the redmine_sla plugin in the list. Is it in the "/opt/redmine/plugins" folder with your other plugins ?

**Comment by likehopper** [comment]
Did you solve your issue? Without more information, it's difficult for me to process.
Without further feedback by the end of next week, I will close this issue.
You can always open a new one later if necessary.

**Comment by likehopper** [comment]
Thank you for trying the plugin, you can open open a new issue if you still have a problem and more information.
