### ISSUE TITLE
function modded to let plugin works

### ISSUE THREAD

**Issue by trogloraspa** [likehopper/redmine_sla#5]
Hello, I had to modify the function sla_get_date( timespamp WITH TIME ZONE), I'm not getting where I have to modify my system to use the configuration u made.

**Comment by likehopper** [comment]
This function can be altered in the Postgres database.  This is what you want ?

**Comment by trogloraspa** [comment]
I did it, I wonder what's the cause that lead me to need to mod it.

**Comment by likehopper** [comment]
What change did you make?

**Comment by trogloraspa** [comment]
sla_get_date( timespamp WITH TIME ZONE),

**Comment by likehopper** [comment]
Could you give me the result of this command : `psql redmine -c "\df"` ?

You should have this result:
```
                                           Liste des fonctions
 Schéma |      Nom      | Type de données du résultat |      Type de données des paramètres       | Type 
--------+---------------+-----------------------------+-------------------------------------------+------
 public | sla_get_date  | timestamp without time zone | p_date timestamp without time zone        | func
 public | sla_get_level | sla_caches                  | p_issue_id integer                        | func
 public | sla_get_spent | sla_cache_spents            | p_issue_id integer, p_sla_type_id integer | func
(3 lignes)
```

**Comment by likehopper** [comment]
Did you solve your issue? Without more information, it's difficult for me to process.
Without further feedback by the end of next week, I will close this issue.
You can always open a new one later if necessary.

**Comment by trogloraspa** [comment]
Sorry  I didn’t have the time to check it again.--S.GensabellaIl giorno 2 nov 2023, alle ore 16:03, LikeHopper ***@***.***> ha scritto:﻿
Did you solve your issue? Without more information, it's difficult for me to process.
Without further feedback by the end of next week, I will close this issue.
You can always open a new one later if necessary.

**Comment by likehopper** [comment]
Thank you for trying the plugin, you can open open a new issue if you still have a problem and more information.
