### ISSUE TITLE
missing column SLA_RESPECT_1

### ISSUE THREAD

**Issue by trogloraspa** [likehopper/redmine_sla#6]
Hi, I get this error:

 ERROR -- : Query::StatementInvalid: PG::UndefinedColumn: ERROR:  column issues.sla_respect_1 does no
LINE 1: ... FROM issue_statuses WHERE is_closed=FALSE)) AND (issues.sla...

any clue?

thanks

**Comment by likehopper** [comment]
When do you get this error ?

**Comment by trogloraspa** [comment]
when I try to apply a filter for the issues that have a sla.

**Comment by likehopper** [comment]
I didn't specify it in the documentation, but for now, after defining "sla_type", you have to "restart" Redmine to create the necessary virtual functions. Maybe it comes from that. Can you restart Redmine?

**Comment by trogloraspa** [comment]
After a restart I dont see the error anymore. but I dont see any sla behave too. I think u should provide a pre-set for the sla setting just to better understand how should this plugin is meant to work.

**Comment by likehopper** [comment]
On a test environment, it's possible to use fixture datas : "https://github.com/likehopper/redmine_sla/blob/main/doc/TESTING.md".
But, I will indeed provide a pre-set and improve the documentation on SLAs' definition.

**Comment by likehopper** [comment]
I just added two first simple examples:
- https://github.com/likehopper/redmine_sla/blob/main/doc/EXAMPLE-01.md
- https://github.com/likehopper/redmine_sla/blob/main/doc/EXAMPLE-02.md
Thanks for your feedback!

**Comment by likehopper** [comment]
I completed it with a third, more complex example.
I developed a bash' script to generate each example.
Don't hesitate to open an issue if there are any problem.
