### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by vinodrenu** [likehopper/redmine_sla#7]
Adding screenshots on the plugin page or here in Github will be helpful for the new users.

**Comment by likehopper** [comment]
Yes, I'll prepare a first " step by step " presentation of a simple configuration to add in documentation.

**Comment by likehopper** [comment]
I just added two first simple examples:
- https://github.com/likehopper/redmine_sla/blob/main/doc/EXAMPLE-01.md
- https://github.com/likehopper/redmine_sla/blob/main/doc/EXAMPLE-02.md
Thanks for your feedback!

**Comment by vinodrenu** [comment]
Thank You. Much appreciated.

**Comment by likehopper** [comment]
I will continue with a more complex example (taking into account interventions during non-working hours)
