### ISSUE TITLE
Error on install to migrate db

### ISSUE THREAD

**Issue by genzo76** [likehopper/redmine_sla#9]
Hi, 
can you help me?
I have a problem when try to install the plugin, you can read the log at follow:

I use this version of redmine:
Environment:
  Redmine version                5.0.5.stable
  Ruby version                   3.1.3-p185 (2022-11-24) [x86_64-linux]
  Rails version                  6.1.7.2
  Environment                    production
  Database adapter               PostgreSQL
 
Log Error:

$ rake redmine:plugins:migrate NAME=redmine_sla
rake aborted!
LoadError: cannot load such file -- listen
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/opt/redmine-5.0.5/config/environments/development.rb:58:in `block in <top (required)>'
/opt/redmine-5.0.5/config/environments/development.rb:5:in `<top (required)>'
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/opt/redmine-5.0.5/config/environment.rb:16:in `<top (required)>'
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by likehopper** [comment]
Is Redmine functional without the redmine_sla plugin?

**Comment by genzo76** [comment]
Yes,  have the problem only with this. The problem is the db update

**Comment by likehopper** [comment]
Could you running task with --trace ?

**Comment by likehopper** [comment]
Did you solve your issue? Without more information, it's difficult for me to process.
Without further feedback by the end of next week, I will close this issue.
You can always open a new one later if necessary.

**Comment by likehopper** [comment]
Thank you for trying the plugin, you can open open a new issue if you still have a problem and more information.
